### ISSUE TITLE
Sagitta温度テレメ送出頻度を調整する

### ISSUE THREAD

**Issue by 200km** [ut-issl/s2e-aobc#10]
## 概要
Sagitta温度テレメ送出頻度を調整する

## 詳細
SILS時に、C2A側では受信頻度につき1フレーム分のテレメのみ解釈できる。温度、クウォータニオンの順に送信してしまうと、より重要なクウォータニオンの情報が得られないため、温度テレメの頻度を下げる。または、SILS時には温度テレメを下ろさない。

## close条件
解決したら

## 備考
NA

## 注意
NA

**Comment by seki-hiro** [comment]
テレメ送出頻度を工夫して対処済んでました。
